/*********************************************************************************************
 * This code was automatically generated by Digital Twin Code Generator tool 0.6.8.
 *
 * Generated Date: 2/24/2020
 *********************************************************************************************/

#include "pnp_device.h"

// Number of Digital Twins interfaces that this device supports.
#define DIGITALTWIN_INTERFACE_NUM 9

#define DEVICEINFO_INDEX 0

#define FIRMWARE_INDEX 1

#define ACC_INDEX 2

#define MAG_INDEX 3

#define GYRO_INDEX 4

#define TEMP_INDEX 5

#define PRESS_INDEX 6

#define HUM_INDEX 7

#define MIC_INDEX 8

#define DEFAULT_SEND_TELEMETRY_INTERVAL_MS 3000

#define DEVICE_CAPABILITY_MODEL_URI "urn:st:stbox1:azure1:1"

static DIGITALTWIN_INTERFACE_CLIENT_HANDLE interfaceClientHandles[DIGITALTWIN_INTERFACE_NUM];
static TICK_COUNTER_HANDLE tickcounter = NULL;
static tickcounter_ms_t lastTickSend;

static int serial_port;

int pnp_device_initialize(const char* connectionString, const char* trustedCert)
{

    serial_port = InitializeSensorTile("/dev/ttyACM0");

    if ((tickcounter = tickcounter_create()) == NULL)
    {
        LogError("tickcounter_create failed");
        return -1;
    }

    DIGITALTWIN_DEVICE_CLIENT_LL_HANDLE digitalTwinDeviceClientHandle = NULL;
    memset(&interfaceClientHandles, 0, sizeof(interfaceClientHandles));

    // Initialize DigitalTwin device handle
    if ((digitalTwinDeviceClientHandle = DigitalTwinClientHelper_InitializeDeviceHandle(connectionString, false, trustedCert)) == NULL)
    {
        LogError("DigitalTwinClientHelper_InitializeDeviceHandle failed");
        return -1;
    }

    // Invoke to the ***Interface_Create - implemented in a separate library - to create DIGITALTWIN_INTERFACE_CLIENT_HANDLE.
    // NOTE: Other than creation and destruction, NO operations may occur on any DIGITALTWIN_INTERFACE_CLIENT_HANDLE
    // until after we've completed its registration (see DigitalTwinClientHelper_RegisterInterfacesAndWait).

    if ((interfaceClientHandles[DEVICEINFO_INDEX] = DeviceInfoInterface_Create(digitalTwinDeviceClientHandle)) == NULL)
    {
        LogError("DeviceInfoInterface_Create failed");
        return -1;
    }

    if ((interfaceClientHandles[FIRMWARE_INDEX] = FirmwareInterface_Create(digitalTwinDeviceClientHandle)) == NULL)
    {
        LogError("FirmwareInterface_Create failed");
        return -1;
    }

    if ((interfaceClientHandles[ACC_INDEX] = AccInterface_Create(digitalTwinDeviceClientHandle)) == NULL)
    {
        LogError("AccInterface_Create failed");
        return -1;
    }

    if ((interfaceClientHandles[MAG_INDEX] = MagInterface_Create(digitalTwinDeviceClientHandle)) == NULL)
    {
        LogError("MagInterface_Create failed");
        return -1;
    }

    if ((interfaceClientHandles[GYRO_INDEX] = GyroInterface_Create(digitalTwinDeviceClientHandle)) == NULL)
    {
        LogError("GyroInterface_Create failed");
        return -1;
    }

    if ((interfaceClientHandles[TEMP_INDEX] = TempInterface_Create(digitalTwinDeviceClientHandle)) == NULL)
    {
        LogError("TempInterface_Create failed");
        return -1;
    }

    if ((interfaceClientHandles[PRESS_INDEX] = PressInterface_Create(digitalTwinDeviceClientHandle)) == NULL)
    {
        LogError("PressInterface_Create failed");
        return -1;
    }

    if ((interfaceClientHandles[HUM_INDEX] = HumInterface_Create(digitalTwinDeviceClientHandle)) == NULL)
    {
        LogError("HumInterface_Create failed");
        return -1;
    }

    if ((interfaceClientHandles[MIC_INDEX] = MicInterface_Create(digitalTwinDeviceClientHandle)) == NULL)
    {
        LogError("MicInterface_Create failed");
        return -1;
    }

    // Register the interface(s) we've created with Azure IoT.  This call will block until interfaces
    // are successfully registered, we get a failure from server, or we timeout.
    if (DigitalTwinClientHelper_RegisterInterfacesAndWait(digitalTwinDeviceClientHandle, DEVICE_CAPABILITY_MODEL_URI, interfaceClientHandles, DIGITALTWIN_INTERFACE_NUM) != DIGITALTWIN_CLIENT_OK)
    {
        LogError("DigitalTwinClientHelper_RegisterInterfacesAndWait failed");
        return -1;
    }

    DigitalTwinClientHelper_Check();

    // report properties

    DeviceInfoInterface_Property_ReportAll();

    FirmwareInterface_Property_ReportAll();

    tickcounter_get_current_ms(tickcounter, &lastTickSend);
    return 0;
}

void pnp_device_run()
{
    tickcounter_ms_t nowTick;
    tickcounter_get_current_ms(tickcounter, &nowTick);

    if (nowTick - lastTickSend >= DEFAULT_SEND_TELEMETRY_INTERVAL_MS)
    {
        LogInfo("Send telemetry data to IoT Hub");

        AccInterface_Telemetry_SendAll();

        MagInterface_Telemetry_SendAll();

        GyroInterface_Telemetry_SendAll();

        TempInterface_Telemetry_SendAll();

        PressInterface_Telemetry_SendAll();

        HumInterface_Telemetry_SendAll();

        MicInterface_Telemetry_SendAll();

        tickcounter_get_current_ms(tickcounter, &lastTickSend);
    }
    else
    {
        // Just check data from IoT Hub
        DigitalTwinClientHelper_Check();
    }
}

void pnp_device_close()
{
    if (interfaceClientHandles[DEVICEINFO_INDEX] != NULL)
    {
        DeviceInfoInterface_Close(interfaceClientHandles[DEVICEINFO_INDEX]);
    }

    if (interfaceClientHandles[FIRMWARE_INDEX] != NULL)
    {
        FirmwareInterface_Close(interfaceClientHandles[FIRMWARE_INDEX]);
    }

    if (interfaceClientHandles[ACC_INDEX] != NULL)
    {
        AccInterface_Close(interfaceClientHandles[ACC_INDEX]);
    }

    if (interfaceClientHandles[MAG_INDEX] != NULL)
    {
        MagInterface_Close(interfaceClientHandles[MAG_INDEX]);
    }

    if (interfaceClientHandles[GYRO_INDEX] != NULL)
    {
        GyroInterface_Close(interfaceClientHandles[GYRO_INDEX]);
    }

    if (interfaceClientHandles[TEMP_INDEX] != NULL)
    {
        TempInterface_Close(interfaceClientHandles[TEMP_INDEX]);
    }

    if (interfaceClientHandles[PRESS_INDEX] != NULL)
    {
        PressInterface_Close(interfaceClientHandles[PRESS_INDEX]);
    }

    if (interfaceClientHandles[HUM_INDEX] != NULL)
    {
        HumInterface_Close(interfaceClientHandles[HUM_INDEX]);
    }

    if (interfaceClientHandles[MIC_INDEX] != NULL)
    {
        MicInterface_Close(interfaceClientHandles[MIC_INDEX]);
    }

    DigitalTwinClientHelper_DeInitialize();
}
