/*********************************************************************************************
 * This code was automatically generated by Digital Twin Code Generator tool 0.6.7.
 *
 * Generated Date: 2/24/2020
 *********************************************************************************************/

#ifndef PNP_DEVICE
#define PNP_DEVICE

#include "digitaltwin_device_client_ll.h"
#include "digitaltwin_interface_client.h"
#include "azure_c_shared_utility/threadapi.h"
#include "azure_c_shared_utility/tickcounter.h"
#include "utilities/digitaltwin_client_helper.h"

#include "utilities/deviceinfo_interface.h"

#include "utilities/firmware_interface.h"

#include "utilities/acc_interface.h"

#include "utilities/mag_interface.h"

#include "utilities/gyro_interface.h"

#include "utilities/temp_interface.h"

#include "utilities/press_interface.h"

#include "utilities/hum_interface.h"

#include "utilities/mic_interface.h"

#include "azure1_impl.h"

#ifdef __cplusplus
extern "C"
{
#endif

int pnp_device_initialize(const char* connectionString, const char* trustedCert);

void pnp_device_run();

void pnp_device_close();

#ifdef __cplusplus
}
#endif

#endif // PNP_DEVICE
